### PR TITLE
Clean up organization of dataset statistics

### PR DESCRIPTION
**Pull request by NoraLoose**
This PR cleans up the organization of the dataset statistics:

1. Gives directories more intuitive names: 
- `variable_distributions` --> `dataset_statistics` (in accordance with naming convention in supplementary information, section 2.3)
- subdirectories: `mli2DVar` --> `input2D` etc.

2. Cleans up code subdirectory:
- Removes submission scripts
- Removes duplicate python scripts

3. Removes duplicate `*.txt` and `*.png` files
4. Populate README with directory structure and explanation

**ToDo**:
* I tried to identify all duplicate files in `variable_distributions/tendency/`. The only ones I'm not sure about are the ones of the form `tendstate_q0001_lev_01_tend.png`, `tendstate_t_lev_01_tend.png` etc. @jerrylin96 @sungdukyu maybe you know which distributions these figures contain?
* @sungdukyu: If you agree with the new naming convention to call this directory `dataset_statistics`, could you change the path in the manuscript from https://github.com/leap-stc/ClimSim/tree/main/variable_distributions to  https://github.com/leap-stc/ClimSim/tree/main/dataset_statistics?

### CODE REVIEW

**Comment by sungdukyu** [comment]
@NoraLoose I agree with your naming convention -- much easier to guess what they are.

BTW, I just updated the weblink in the manuscript, so please go ahead with changing the dir name:
from https://github.com/leap-stc/ClimSim/tree/main/variable_distributions
to https://github.com/leap-stc/ClimSim/tree/main/dataset_statistics

Thank you!

**Comment by NoraLoose** [comment]
Thanks @sungdukyu! 

In addition to changing the directory names, I am trying to clean up the `variable_distributions/tendency/` directory. Do you know which distributions are shown in 
* https://github.com/leap-stc/ClimSim/blob/main/variable_distributions/tendency/tendstate_q0001_lev_01_tend.png
* https://github.com/leap-stc/ClimSim/blob/main/variable_distributions/tendency/tendstate_t_lev_01_tend.png

**Comment by sungdukyu** [comment]
@NoraLoose Based on the variable name "tendstate", it must be ptend_t (Heating tendency, dT/dt [K/s]) and ptend_q0001 (Moistening tendency, dq/dt [kg/kg/s]).

(BTW, @liranpeng produced the data stats.)

**Comment by NoraLoose** [comment]
I'm merging this since this is just a simple re-organization and @sungdukyu has agreed to it!

**Pull request merged**
